# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('Teacher_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Teacher_FName', models.CharField(max_length=20)),
            ],
        ),
    ]
