# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherdirectory', '0003_auto_20171118_1638'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentDoc',
            new_name='TeacherDoc',
        ),
    ]
